### ISSUE TITLE
nepcal global options are not working

### ISSUE THREAD

**Issue by mesaugat** [srishanbhattarai/nepcal#32]
Probably is an issue with `urfave/cli`. Cannot be sure as I have not taken a deeper look.

https://github.com/urfave/cli/issues/546

Output right now. 

```
$ nepcal -v

flag provided but not defined: -v
Usage of nepcal:
```

```
$ nepcal -h

Usage of nepcal:
```

**Comment by srishanbhattarai** [comment]
Hmm, most likely an upstream issue. I'll check it out too. Thanks for reporting!
