### ISSUE TITLE
Convert BS to AD

### ISSUE THREAD

**Issue by anarchyrucks** [srishanbhattarai/nepcal#40]
Hi, I'm interested in solving this issue. I've already implemented this in the current codebase, but I'll wait to create the PR until the restructuring in #35 is completed. Thanks.

**Comment by srishanbhattarai** [comment]
Hi, thanks for taking this!

I am hesitant about landing #35 because it breaks some downstream projects and might even close it. I would recommend that you create your branch off of the current head instead of waiting for #35.

**Comment by anarchyrucks** [comment]
Sure I can do that. I wanted to wait for #35 because it seems to have better structure overall and some kludgy parts of the code could be weeded out. Thanks.

**Comment by srishanbhattarai** [comment]
Fully agree but having downstream projects is what's stopping that from landing. The project's goals have changed from its genesis so there is a lot of weeding out that needs to happen.

To me, the best way forward seems to be to create a  `v2/` library with the niceties in #35. But for this issue, I'd be grateful if you just went with whatever is present.

**Comment by anarchyrucks** [comment]
Closing since #41 is merged.
