### ISSUE TITLE
Show calendar weekdays in Nepali 

### ISSUE THREAD

**Issue by srishanbhattarai** [srishanbhattarai/nepcal#56]
This needs to happen for:
1. the `Stringer` interface on `nepcal.Weekday` 
2. the CLI calendar needs to use abbreviated versions, using a new method (e.g. `Abbr()`)
3. Change README calendars as well

For easy copy pasta:
```
Sunday आइतवार
Monda सोमवार
Tuesday मङ्गलवार
Wednesday बुधवार
Thursday बिहिवार
Friday शुक्रवार
Saturday शनिवार
```

**Comment by mesaugat** [comment]
```diff
- Show calendar month names in Nepali
+ Show calendar weeks in Nepali
```

**Comment by mesaugat** [comment]
You wrote it in Hindi.

```diff
- वार
+ बार
```

```diff
- Monda सोमवार
+ Monday सोमबार
```

```diff
- Tuesday मङ्गलवार
+ Tuesday मंगलबार
```

**Comment by srishanbhattarai** [comment]
I copied it from a Nepali site 😆

**Comment by mesaugat** [comment]
I say that's wrong.

**Comment by mesaugat** [comment]
I did this but I don't want to do fix the tab spacing and all. 

     चैत १४, २०७६
 आइत सोम मंगल बुध बिहि शुक्र शनि 
                             १
 २   ३   ४    ५   ६    ७     ८
 ९   १०  ११   १२  १३   १४    १५
 १६  १७  १८   १९  २०   २१    २२
 २३  २४  २५   २६  २७   २८    २९
 ३०

**Comment by srishanbhattarai** [comment]
<img width="173" alt="Screen Shot 2020-12-31 at 8 56 37 PM" src="https://user-images.githubusercontent.com/24712573/103432751-ad5cdd80-4baa-11eb-8d3f-eecde26cf39c.png">

This works now.

**Comment by srishanbhattarai** [comment]
Closing, for now. I may work on a better elastic tabstop and resuscitate this issue.
