### ISSUE TITLE
Can we have a pypi package of this application?

### ISSUE THREAD

**Issue by designjeevan** [srishanbhattarai/nepcal#68]
Hi. this seems a great utility for BS calendar. 
If it's not asking too much, if we could have a pypi version of this application with basic datetime operations, it would be great for python developers.

**Comment by srishanbhattarai** [comment]
Hmm, it's an interesting question but practically speaking I don't know how useful that would be relative to the effort required. 

Re-writing is not an option for me, and maintaining two separate libraries does not sound fun. Also, just porting the code is going to be a bit tedious, even though it's not complicated.

The other option is to use the C ABI as an intermediary and export a shared library from the current code, that would be loaded by Python which is *probably* easier, but the Python clients would be loading in the entire Go runtime for some simple date time calculations in that case.

If you have simple use cases, feel free to copy/paste the code from this repository and apply it to your situation. It's fairly simple Go code and is well documented (I think).
