### ISSUE TITLE
Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by jprokos** [srishanbhattarai/nepcal#76]
Just seeing this for the first time today. 
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the srishanbhattarai/nepcal tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/srishanbhattarai/homebrew-nepcal/Formula/nepcal.rb:6
```

**Comment by jprokos** [comment]
https://stackoverflow.com/questions/45132704/what-does-bottle-unneeded-do/45163490#45163490

It looks like you can just remove the line to solve this issue.

**Comment by srishanbhattarai** [comment]
Yep, thanks for the link. I did read that somewhere else as well. 

That Ruby snippet was generated by `goreleaser`, and I don't want to have to fight either `goreleaser` or Homebrew when making future releases. Seeing [this](https://github.com/goreleaser/goreleaser/pull/2591/files) gives me more confidence though.

**Comment by jprokos** [comment]
FYI I had to uninstall/untap and then retap/reinstall for this to work. No issues that I can see so far. Thank you.

**Comment by srishanbhattarai** [comment]
Right, thanks for letting me know! I think that's just how Homebrew does things. I'm hoping people who choose to upgrade don't face any issues..
